src/main/java/com/cars/platform/domain/Person.java
package com.cars.platform.domain;

import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Enumerated;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.TypedQuery;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.roo.addon.javabean.RooJavaBean;
import org.springframework.roo.addon.jpa.activerecord.RooJpaActiveRecord;
import org.springframework.roo.addon.tostring.RooToString;

@RooJavaBean
@RooToString
@RooJpaActiveRecord(finders = { "findPeopleByUsernameEquals", "findPeopleByCompany", "findPeopleByPersonRole" })
public class Person {

    private String firstName;
    private String lastName;
    private String email;
    private String title;
    private String password;
    @ManyToOne
    private Company company;
    @Enumerated
    private PersonRole personRole = PersonRole.BASIC;

    private String username;
    private String phone;
    private String passwordResetCode;
    private boolean enabled = true;

    private boolean publicContact;
    private boolean emailRemindersEnabled;
    private boolean emailUploadRemindersEnabled;
    private boolean newFinancialRemindersEnabled;

    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(style = "M-")
    private Date agreementDate;

    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(style = "M-")
    private Date agreementDateSelect;

    public boolean isAdmin() {
	return PersonRole.ADMIN.equals(personRole);
    }

    public boolean isAnalyst() {
	return ((company != null) && (CompanyType.CARS.equals(company.getCompanyType())));
    }

    public boolean isSubscriber() {
	return ((company != null) && (CompanyType.INVESTOR.equals(company.getCompanyType())));
    }

    public String getFullName() {
	String fullName = "";
	if (firstName != null) {
	    fullName += firstName;
	}
	fullName += " ";
	if (lastName != null) {
	    fullName += lastName;
	}
	return fullName;
    }

    public static List<Person> findAnalysts() {
	TypedQuery<Person> q = entityManager().createQuery("SELECT o FROM Person o where o.company.companyType = :companyType and o.personRole = :personRole", Person.class);
	q.setParameter("companyType", CompanyType.CARS);
	q.setParameter("personRole", PersonRole.BASIC);

	return q.getResultList();
    }

    public static boolean isUsernameInUse(String username) {
	boolean inUse = false;
	try {

	    Person person = Person.findPeopleByUsernameEquals(username);
	    if (null != person) {
		    inUse = true;
	    }
	} catch (Exception ignore) {
	}
	return inUse;
    }


	public static Person findPeopleByUsernameEquals(String username) {
        if (username == null || username.length() == 0) throw new IllegalArgumentException("The username argument is required");
        EntityManager em = Person.entityManager();
        TypedQuery<Person> q = em.createQuery("SELECT o FROM Person AS o WHERE o.username = :username", Person.class);
        q.setParameter("username", username);
        return q.getSingleResult();
    }
}

src/main/webapp/WEB-INF/views/header.jspx
<div id="header" xmlns:jsp="http://java.sun.com/JSP/Page"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:spring="http://www.springframework.org/tags" version="2.0">
	<jsp:directive.page contentType="text/html;charset=UTF-8" />
	<jsp:output omit-xml-declaration="yes" />

	<spring:url var="dashboard" value="/" />
	<spring:url var="banner" value="/resources/images/AERIS_CLOUD_LOGO.png" />
	<spring:url var="home" value="/" />
	<spring:url var="cdfi" value="/cdfi" />
	<spring:url var="logout" value="/resources/j_spring_security_logout" />
	<spring:url var="profile" value="/profile/mine" />
	<spring:url var="usermanagement" value="/usermanagement" />
	<spring:url var="platformmanagement" value="/documenttypes" />
	<spring:url var="myservices" value="/myservices" />
	<spring:url var="myreports" value="/investor/${person.company.id }/myreports" />
	<spring:url var="carsservices" value="/carsservices" />
	<spring:url var="messagecenter" value="/message" />
	<spring:url var="toolsandresources"
		value="/cdfi/${person.company.id }/library" />
	<spring:url var="mydata" value="/cdfi/${person.company.id}/ratings" />

	<spring:message code="button_home" var="home_label" htmlEscape="false" />
	
	<c:if
		test="${(person==null)||(!(person.company.CARS) &amp;&amp;(person.agreementDate==null))}">
		<!--c:redirect url="${dashboard }" /-->
	</c:if>

	<c:set var="path"
		value="${requestScope['javax.servlet.forward.request_uri']}" />

	<div style="float: left; margin-left:10px; margin-top:10px; margin-bottom:10px;">
		<a href="${home}" name="${fn:escapeXml(home_label)}"
			title="${fn:escapeXml(home_label)}"> <img src="${banner}" style="width:331px;height:24px;" />
		</a>
	</div>
	
	<div id="welcome" style="float: right;  margin-right:10px;">
		<c:if test="${person!=null }">
			<c:if test="${pageContext.request.userPrincipal.name != null}">
		Hello, <a href="${profile}">${person.firstName }</a>
	
		<span style='padding-left: 20px;'><a href="${logout}">Logout</a></span>
			</c:if>
		</c:if>
	</div>

	<div style="clear: both;">
		<!-- placeholder -->
	</div>

	<div id="menuTabsContainer">

		<spring:url var="tabs1aal"
			value="/resources/images/tabs/1a.tabs_active_left.png" />
		<spring:url var="tabs1aam"
			value="/resources/images/tabs/1a.tabs_active_mid.png" />
		<spring:url var="tabs1aar"
			value="/resources/images/tabs/1a.tabs_active_right.png" />

		<ul id="menuTabs" style="right: 0px;">

			<c:choose>

				<c:when test="${fn:endsWith(path, dashboard)}">
					<li id="current"><a href="#">Dashboard</a></li>
				</c:when>
				<c:otherwise>
					<li><a href="${dashboard }">Dashboard</a></li>
				</c:otherwise>
			</c:choose>

			<c:if test="${(person.company.CARS) }">

				<c:choose>
					<c:when
						test="${(fn:contains(path, 'library') || (fn:contains(path, 'selector') &amp;&amp; !fn:contains(path, 'cdfi') &amp;&amp; !fn:contains(path, 'investor')) || fn:contains(path, 'list'))}">
						<li id="current"><a href="#">Tools &amp; Resources</a></li>
					</c:when>
					<c:otherwise>
						<li><a href="${toolsandresources}">Tools &amp; Resources</a></li>
					</c:otherwise>
				</c:choose>
			</c:if>

			<c:if test="${person.admin }">
				<c:choose>
					<c:when test="${fn:endsWith(path, 'usermanagement')}">
						<li id="current"><a href="#">Manage Users</a></li>
					</c:when>
					<c:otherwise>
						<li><a href="${usermanagement }">Manage Users</a></li>
					</c:otherwise>
				</c:choose>
			</c:if>

			<c:if test="${(person.company.CDFI) }">
				<c:choose>
					<c:when test="${fn:contains(path, 'cdfi')&amp;&amp;person.company.id==company.id}">
						<li id="current"><a href="#">My Data</a></li>
					</c:when>
					<c:otherwise>
						<li><a href="${mydata}">My Data</a></li>
					</c:otherwise>
				</c:choose>

				<c:choose>
					<c:when test="${fn:contains(path, 'myservices')}">
						<li id="current"><a href="#">My Services</a></li>
					</c:when>
					<c:otherwise>
						<li><a href="${myservices}">My Services</a></li>
					</c:otherwise>
				</c:choose>
			</c:if>

			<!--c:if test="${hasCdfiAccess}"-->
				<c:if test="${(person.company.investor) }">
				<c:choose>
					<c:when test="${(fn:endsWith(path, 'peergroups') || fn:endsWith(path, 'selector') || fn:endsWith(path, 'distribution') || fn:contains(path, 'myreports')) &amp;&amp; fn:contains(path, 'investor')}">
						<li id="current"><a href="#">My Reports</a></li>
					</c:when>
					<c:otherwise>
						<li><a href="${myreports}">My Reports</a></li>
					</c:otherwise>
				</c:choose>
			</c:if>

			<c:if test="${person.admin }">
				<c:choose>
					<c:when test="${fn:endsWith(path, 'documenttypes')}">
						<li id="current"><a href="#">Manage Platform</a></li>
					</c:when>
					<c:when test="${fn:endsWith(path, 'metriccategories')}">
						<li id="current"><a href="#">Manage Platform</a></li>
					</c:when>
					<c:when test="${fn:endsWith(path, 'metric/index/0')}">
						<li id="current"><a href="#">Manage Platform</a></li>
					</c:when>
					<c:when test="${fn:endsWith(path, 'reportcategorys')}">
						<li id="current"><a href="#">Manage Platform</a></li>
					</c:when>
					<c:when test="${fn:endsWith(path, 'formulas')}">
						<li id="current"><a href="#">Manage Platform</a></li>
					</c:when>
					<c:when test="${fn:endsWith(path, 'graphs')}">
						<li id="current"><a href="#">Manage Platform</a></li>
					</c:when>
					<c:when test="${fn:endsWith(path, 'valuefacts')}">
						<li id="current"><a href="#">Manage Platform</a></li>
					</c:when>
					<c:when test="${fn:contains(path, 'breakdown')}">
						<li id="current"><a href="#">Manage Platform</a></li>
					</c:when>


					<c:otherwise>
						<li><a href="${platformmanagement }">Manage Platform</a></li>
					</c:otherwise>
				</c:choose>
			</c:if>

			<c:choose>
				<c:when test="${fn:contains(path, 'message')}">
					<li id="current"><a href="#">Message Center</a></li>
				</c:when>
				<c:otherwise>
					<li><a href="${messagecenter}">Message Center</a></li>
				</c:otherwise>
			</c:choose>
		</ul>
	</div>

	<div style="clear: both;">
		<!-- placeholder -->
	</div>

</div>

src/main/webapp/WEB-INF/views/index-template.jspx
<div xmlns:spring="http://www.springframework.org/tags" xmlns:util="urn:jsptagdir:/WEB-INF/tags/util" xmlns:jsp="http://java.sun.com/JSP/Page" version="2.0">
  <jsp:directive.page contentType="text/html;charset=UTF-8" />
  <jsp:output omit-xml-declaration="yes" />
  <spring:message var="title" htmlEscape="false" />
  <util:panel id="title" title="${title}">
    <spring:message code="application_name" var="app_name" htmlEscape="false" />
    <h3>
      <spring:message code="welcome_titlepane" arguments="${app_name}" />
    </h3>
  </util:panel>
</div>

src/main/webapp/WEB-INF/views/uncaughtException.jspx
<div style="margin-left:20px;" xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:fn="http://java.sun.com/jsp/jstl/functions" xmlns:util="urn:jsptagdir:/WEB-INF/tags/util" xmlns:spring="http://www.springframework.org/tags" xmlns:jsp="http://java.sun.com/JSP/Page" version="2.0">
  <jsp:directive.page contentType="text/html;charset=UTF-8" />
  <jsp:output omit-xml-declaration="yes" />
  <spring:message var="title" code="error_uncaughtexception_title" htmlEscape="false" />
  <util:panel id="title" title="">
    <h2>${fn:escapeXml(title)}</h2>
    <p>
      <spring:message code="error_uncaughtexception_problemdescription" />
    </p>
    <c:choose>
	    <c:when test="${person.company.CARS }">
		    <c:if test="${not empty exception}">
		      <p>
		        <h4>
		          <spring:message code="exception_details" />
		        </h4>
		        <spring:message var="message" code="exception_message" htmlEscape="false" />
		        <util:panel id="_message" title="${message}" openPane="false">
		          <c:out value="${exception.localizedMessage}" />
		        </util:panel>
		        <spring:message var="stacktrace" code="exception_stacktrace" htmlEscape="false" />
		        <util:panel id="_exception" title="${stacktrace}" openPane="false">
		          <c:forEach items="${exception.stackTrace}" var="trace">
		            <c:out value="${trace}" />
		            <br />
		          </c:forEach>
		        </util:panel>
		      </p>
		    </c:if>
	    </c:when>
	    <c:otherwise>
	    	<p>	       
    			<spring:message code="error_uncaughtexception_contact" />    
	  		</p>
	    </c:otherwise>
    </c:choose>
  </util:panel>
</div>