src/main/java/com/cars/platform/domain/Company.java
package com.cars.platform.domain;

import java.io.Serializable;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.persistence.EntityManager;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.ManyToMany;
import javax.persistence.TypedQuery;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.springframework.roo.addon.javabean.RooJavaBean;
import org.springframework.roo.addon.jpa.activerecord.RooJpaActiveRecord;
import org.springframework.roo.addon.tostring.RooToString;

import com.cars.platform.util.DateHelper;

@RooJavaBean
@RooToString(excludeFields={"requiredMetrics", "analysts"})
@RooJpaActiveRecord(finders = { "findCompanysByCompanyType" })
public class Company implements Serializable, Comparable<Company> {

    //@ManyToMany(fetch=FetchType.EAGER) // in order to avoid no session error in ActionItemService
    @ManyToMany 
    List<Metric> requiredMetrics;

    @NotNull
    @Size(min = 2)
    private String name;

    @Enumerated
    private CompanyType companyType = CompanyType.INVESTOR;

    @Enumerated
    private TaxType taxType = TaxType.NON_PROFIT;
    
    
    private String address;

    private String city;

    private String state;

    private String zip;

    private String phone;

    private int fiscalYearStart = 1;
    
    private int startRequestingYear = DateHelper.getCurrentYear();
    
    private int startRequestingQuarter = 2;

    private boolean rated = true;
    
    private boolean showRatingsTab = true;
    
    // Can subscribers see this CDFI's financials
    @Enumerated
    private ShareFinancials shareFinancials = ShareFinancials.SPECIFIC;
    
    // Can this CDFI be included in a peer group
    private boolean peerGroupAllowed = true;

    private String logo;

    private String address2;

    private String fax;

    private boolean allRows = false;

    @ManyToMany
    List<State> areaServed;

    private String url;

    @Size(max = 1000)
    private String description;
    
    @Size(max = 200)
    private String mission;
    
    // Employee Identification Number, for non profits
    private String EIN;

    @ManyToMany
    List<LendingType> lendingType;
    
    @ManyToMany
    private List<SectoralFocus> sectoralFocus;
    
    @ManyToMany
    private List<TargetBeneficiary> targetBeneficiary;

    private String orgType;

    private boolean active = false;

    @ManyToMany
    private List<Person> analysts;

    private boolean suppress = false;

    private boolean hideActivity = false;
    
    private Date activeDate;

    
    
    // accessors for sectoralFocus and mission weren't being added to Company_Roo_JavaBean for some reason
    public List<SectoralFocus> getSectoralFocus() {
		return sectoralFocus;
	}
	public void setSectoralFocus(List<SectoralFocus> sectoralFocus) {
		this.sectoralFocus = sectoralFocus;
	}
	public List<TargetBeneficiary> getTargetBeneficiary(){
		return targetBeneficiary;
	}
	public void setTargetBeneficiary(List<TargetBeneficiary> targetBeneficiary){
		this.targetBeneficiary = targetBeneficiary;
	}
	public String getMission() {
		return mission;
	}
	public void setMission(String mission) {
		this.mission = mission;
	}
	
	public String getEIN() {
		return EIN;
	}
	public void setEIN(String eIN) {
		EIN = eIN;
	}
	public Date getActiveDate() {
		return activeDate;
	}
	public void setActiveDate(Date activeDate) {
		if (null == this.activeDate) {
		    this.activeDate = activeDate;
		}
	}
	
	public boolean isActive() {
        return this.active;
    }

	public void setActive(boolean active) {
		if (!this.active && active && null == this.activeDate) {
			setActiveDate(new Date());
		}
        this.active = active;
    }
	
	public boolean isEmailValid() {		
		boolean ans = false;
		List<Person> persons = Person.findPeopleByCompany(this).getResultList();
		for (Person person : persons) {
			String emailAddress = person.getEmail();
			if (null == emailAddress)
				continue;
			
			try {
				InternetAddress.parse(emailAddress, true);
				ans = true;
				break;
			} catch (AddressException e) {
				ans = false;
			}				
		}
			
		return ans;
	}
	
	public boolean isCDFI() {
        return CompanyType.CDFI.equals(companyType);
    }

    public boolean isInvestor() {
        return companyType.equals(CompanyType.INVESTOR);
    }

    public boolean isCARS() {
        return companyType.equals(CompanyType.CARS);
    }

    public String getFiscalYearStartString() {
        switch(fiscalYearStart) {
            case 1:
                return "January 01";
            case 2:
                return "February 01";
            case 3:
                return "March 01";
            case 4:
                return "April 01";
            case 5:
                return "May 01";
            case 6:
                return "June 01";
            case 7:
                return "July 01";
            case 8:
                return "August 01";
            case 9:
                return "September 01";
            case 10:
                return "October 01";
            case 11:
                return "November 01";
            case 12:
                return "December 01";
            default:
                return "";
        }
    }

    public String getFiscalYearEndString() {
        switch(fiscalYearStart) {
            case 1:
                return "December 31";
            case 2:
                return "January 31";
            case 3:
                return "February 28";
            case 4:
                return "March 31";
            case 5:
                return "April 30";
            case 6:
                return "May 31";
            case 7:
                return "June 30";
            case 8:
                return "July 31";
            case 9:
                return "August 31";
            case 10:
                return "September 30";
            case 11:
                return "October 31";
            case 12:
                return "November 30";
            default:
                return "";
        }
    }

    public String getAreaServedString() {
        boolean first = true;
        String areaServedString = "";
        for (State areaServed : this.getAreaServed()) {
            if (!first) areaServedString += ", ";
            first = false;
            areaServedString += areaServed.getStateCode();
        }
        return areaServedString;
    }

    public String getLendingTypeString() {
        boolean first = true;
        String lendingTypeString = "";
        for (LendingType lendingType : this.getLendingType()) {
            if (!first) lendingTypeString += ", ";
            first = false;
            lendingTypeString += lendingType.getName();
        }
        return lendingTypeString;
    }
    
    public String getSectoralFocusString() {
        boolean first = true;
        String sectoralFocusString = "";
        for (SectoralFocus sectoralFocus : this.getSectoralFocus()) {
            if (!first) sectoralFocusString += ", ";
            first = false;
            sectoralFocusString += sectoralFocus.getName();
        }
        return sectoralFocusString;
    }
    
    // since zip is stored as an int. Boston zip for example start with zero
    public String getZipString() {
    	// Initially zip was defined as an int (but a string in the database) this resulted in zips with leading zeros
    	// being stored as 4 digits
    	if (zip.length() == 4) {
    		int zipInt = Integer.parseInt(zip);
        	return String.format("%05d", zipInt);
    	}
    	
    	return zip;
    }

    public static List<com.cars.platform.domain.Company> findAllCompanysAlphabetically() {
        EntityManager em = Company.entityManager();
        return em.createQuery("SELECT o FROM Company o order by o.name", Company.class).getResultList();
    }

    public Review getMostRecentCompletedFullAnalysisReview() {
    	return Review.findMostRecentCompletedFullAnalysisReview(this);
    }
    
    public String getRating() {
        String rating = "";
        Review review = getMostRecentCompletedFullAnalysisReview();
        if (review != null) {
            if (review.getImpactPerformance() != null) rating += review.getImpactPerformance();
            if (review.isPolicyPlus()) rating += " policy plus ";
            if (review.getFinancialStrength() != null) rating += " " + review.getFinancialStrength();
        }
        return rating;
    }

    public String getRatedSince() {
        String ratedSince = "";
        Review review = Review.findEarliestCompletedFullAnalysisReview(this);
        if (review != null && review.getDateOfAnalysis() != null) {
            Calendar cal = Calendar.getInstance();
            cal.setTime(review.getDateOfAnalysis());
            ratedSince = Integer.toString(cal.get(Calendar.YEAR));
        }
        return ratedSince;
    }
    
    public Double getTotalAssets() {
    	Equation totalAssetsEquation = Equation.findTotalAssets();
    	Period period = Period.findMostRecentAuditOrInternalPeriod(this);
    	if (null == period) {
    		return null;
    	}
    	PeriodDim periodDim = PeriodDim.findByPeriod(period);
    	
    	ValueFact totalAssetFact = ValueFact.findValueFact(periodDim, totalAssetsEquation, this);
    	if (null == totalAssetFact) {
    		return null;
    	}
    	return totalAssetFact.getAmount();
    }
    
    public String getTotalAssetsString() {
    	Double totalAssets = getTotalAssets();
    	if (null == totalAssets) {
    		return "No financial data is currently available";
    	}
    	else {
    	    NumberFormat currencyFormat = NumberFormat.getCurrencyInstance();
    	    currencyFormat.setMaximumFractionDigits(0);
    	    currencyFormat.setMinimumFractionDigits(0);
    	    return currencyFormat.format(totalAssets);

src/main/webapp/WEB-INF/views/subscriber/show.jspx
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<div xmlns:jsp="http://java.sun.com/JSP/Page" 
     xmlns:spring="http://www.springframework.org/tags" 
     xmlns:c="http://java.sun.com/jsp/jstl/core"
	 xmlns:sform="http://www.springframework.org/tags/form"
	 xmlns:fmt="http://java.sun.com/jsp/jstl/fmt"
	 xmlns:tiles="http://tiles.apache.org/tags-tiles"
	 xmlns:util="urn:jsptagdir:/WEB-INF/tags/util" version="2.0">
  <jsp:directive.page contentType="text/html;charset=UTF-8"/>
  <jsp:output omit-xml-declaration="yes"/>
  <spring:message code="label_subscriber_index" htmlEscape="false" var="title"/>
  <spring:message code="application_name" htmlEscape="false" var="app_name"/>
  <spring:url var="dashboard" value="/" />
  <spring:url var="profile" value="/profile" />
  <spring:url var="subscriber" value="/subscriber" />
  
  <spring:url var="icon_blank" value="/resources/images/icon_blank.png" />
 
  <spring:url var="usermanagement" value="/usermanagement" />
	<!-- OPS or ANALYST user only can see this page -->

<style>
.info {
	text-align: left;
	width: auto;
	border: 0px solid #ffffff;
}

.info td {
	height: 12px;
	font-size: 12px;
	/*white-space: nowrap;*/
	border: 0px solid #ffffff;
}

.info tr {
	background-color: #FFFFFF;
}

#carsmain {max-width: 722px;}

</style>


    <script>
	<![CDATA[
    $(function() {
        $('.confirmation').on('click', function () {
            return confirm('Are you sure?');
        });  
    });

    ]]>
    </script>

    <h3>Activity</h3>


	<c:if test="${activity.size()==0 }">
	    <p><i>No recent subscriber activity.</i></p>
    </c:if>
						
	<c:forEach var="activity" items="${activity }">
	    <p style="line-height:12px;"><b>${activity.person.firstName} ${activity.person.lastName}</b> ${activity.summary }</p>						
	</c:forEach>	

    <div style="float:left;width:50%;">

    <h3>Organization Details</h3>

    <table class="info">

        <tr><td width="80"><b>Address:</b></td>
        <td width="180">${company.address }<br/>${company.city }, ${company.state } ${company.zipString }</td>
        <td>
          <span id="icon-update"><a href="${subscriber }/${company.id }/edit"><img src="${icon_blank }" title="Edit" style="padding-right:10px;"/></a></span>       
          <span id="icon-delete"><a href="${subscriber }/delete/${company.id}" class="confirmation"><img src="${icon_blank }" title="Delete" style="padding-right:10px;"/></a></span>
        </td>                  
        </tr>
        <tr><td><b>Phone:</b></td>
        <td>${company.phone }</td><td></td></tr>
        <tr><td><b>Fax:</b></td>
        <td>${company.fax }</td><td></td></tr>
          
    </table>
    </div>







    <div style="float:right;width:50%;">
    
    
    
    
    <h3>Contacts</h3>


    <table class="info">
    <c:forEach var="employee" items="${employees }">
        <tr><td width="80"><b>Username:</b></td>
        <td width="180">${employee.username }</td>
    
        <td> 
        <span id="icon-update"><a href="${profile }/${employee.id}"><img src="${icon_blank }" title="Edit" style="padding-right:10px;"/></a></span>
        <span id="icon-delete"><a href="${profile }/delete/${employee.id}" class="confirmation"><img src="${icon_blank }" title="Delete" style="padding-right:10px;"/></a></span>
        
        </td>
        </tr>
        <tr><td><b>Password:</b></td>
        <td>${employee.password }</td><td></td></tr>     
        <tr><td><b>Name:</b></td>
        <td>${employee.firstName } ${employee.lastName }</td><td></td></tr>
        <tr><td><b>Title:</b></td>
        <td>${employee.title }</td><td></td></tr>
       <tr><td><b>Email:</b></td>
        <td>${employee.email }</td><td></td></tr>
       <tr><td><b>Reminders:</b></td>
        <td>${employee.emailRemindersEnabled }</td><td></td></tr>
        <tr><td><b>Upload Reminders:</b></td>
        <td>${employee.emailUploadRemindersEnabled }</td><td></td></tr>
        <tr><td><b>New Financial Reminders:</b></td>
        <td>${employee.newFinancialRemindersEnabled }</td><td></td></tr>
        <tr><td><b>Public Contact:</b></td>
        <td>${employee.publicContact }</td><td></td></tr>
       <tr><td><b>Phone:</b></td>
        <td>${employee.phone }</td><td></td></tr>
        <tr><td><b>Reporting Agreement:</b></td>
         <td><fmt:formatDate pattern="MM/dd/yyyy" value="${employee.agreementDate }" /></td><td></td></tr>
        <tr><td><b>Aeris Select Agreement:</b></td>
         <td><fmt:formatDate pattern="MM/dd/yyyy" value="${employee.agreementDateSelect }" /></td><td></td></tr>


 


       <tr><td colspan="3">&#160;</td></tr>
     </c:forEach>
    </table>
    
    
    <p>
    <a href="${profile }?form&amp;companyId=${company.id}">Add new contact</a>
    </p>
    
    
    </div>
    
    <br clear="both"/>

	<tiles:insertTemplate template="/WEB-INF/views/message/send.jspx"/>
</div>